### ISSUE TITLE
Atividades

### ISSUE THREAD

**Issue by leonascimento** [Jessica7/Best-links-sass#16]
Bom seria legal fazermos um resumo aqui publicar ideias ou relacionados pra movimentamos esse repositório discutirmos e criarmos componentes ou discutirmos através de um live codding ou usarmos um chat como o  https://gitter.im/ pra fazer perguntas e discutirmos coisas legais e aí meninas @rubiadias  e @Jessica7 ?

**Comment by Jessica7** [comment]
Excelente! então tudo vamos conversar lá pelo  https://gitter.im/ fica certo assim ?
