### ISSUE TITLE
Conflitos

### ISSUE THREAD

**Issue by andersonweb** [Jessica7/Best-links-sass#2]
Olá, tudo bem? 
Acho que já existe um projeto bem semelhante a esse. Segue o [link](https://github.com/HugoGiraudel/awesome-sass). 
Mas se a ideia for diferente, perdão!

**Comment by Jessica7** [comment]
Olá Anderson! esse repositório tem o objetivo apenas de compartilhar links entre um pequeno grupo: @leonascimento  e @rubiaDias  nós estamos implementando alguns projetos e estamos utilizando Sass , então achamos mais conveniente criar esse repositório para compartilhar nossos links sobre o assunto(não temos intensão de divulgar). Mas muitíssimo obrigada pela dica :)  para evitar algum problema mudarei o nome do repositório vlw :+1:  Caso queira contribuir com algum link bacana fique à vontade.

**Comment by andersonweb** [comment]
Opa! Ahh, tudo bem! pode deixar, se eu puder compartilhar, partilharei.
De imediato, posso te passar esse link [aqui](https://github.com/andersonweb/R-A-D/blob/master/source/sass/readme.md), contém alguns, artigos falando sobre sass.
Sucessos!

**Comment by rubiadias** [comment]
Oi pessoal! Tudo bem? Agora vai heim?rs
Tentei compartilhar algumas coisas aqui ontem @Jessica7 mas, está dando um erro de SSH e mais não sei o que... rs

**Comment by andersonweb** [comment]
@rubiadias publica o erro aqui, um foto... quem sabe não posso te ajudar :)

**Comment by leonascimento** [comment]
@rubiadias será que é porque @Jessica7  mudou o nome do repositório...
* Tentar deleta ele e dar um star novamente.
Vi que Jéssica alterou o nome de awesome-sass para Best-links-sass.
Outra coisa também Rúbia é que na época que você deu um star, de lá pra cá ela já deve ter atualizado com novos links você deveria fazer um rebase para atualizar. E logo após fazer o pull request. Esse link aqui me ajudou pra caramba. Qualquer coisa posta aqui o link... Eu tbm me enrolo muito com o git. rsrsrsrs
http://blog.da2k.com.br/2014/01/19/manter-repositorio-github-forkado-sincronizado-com-o-original/

**Comment by Jessica7** [comment]
@rubiadias tenta seguir o que Léo te sugeriu, comigo já aconteceu isso tbm e era justamente quando o repositório não estava atualizado! qualquer coisa pode gritar aqui!
